例外対策として、try {}catch文が良く使われる
例外対策には二通りあり、処理を作るか作らないかの2択である。

```java
import java.io.*;

public class Main17_1{
  public static void main(String [] args) {
   try{
    FileReader fr = new FileReader("data.txt");//ファイルを開く//newするときに例外が発生するかもしれないので例外処理をおこなう
    int input = fr.read();//②ファイルから1文字読み込む戻り値int
    while(input != -1){  //読み込んだ文字がファイルの末尾が（-1）でない間繰り返す
      System.out.print((char)input);
      input = fr.read();//次の文字を読み込む
    }
    System.out.println(" ");
    fr.close();//ファイルを閉じる
   }catch (FileNotFoundException e) {//①の例外
      System.out.println("エラーが発生しました");
      e.printStackTrace();

   }catch (IOException e) {//②の例外
      System.out.println("エラーが発生しました");
      e.printStackTrace();
   }
   System.out.print("プログラムは正常に終了しました。");
  }
}	
書き方を間違えないする。

もしわからない場合には670

 }catch (Exception e) {//①の例外
      System.out.println("エラーが発生しました");
      e.printStackTrace();
